### ISSUE TITLE
可以帮忙解答一个蠢笨的问题吗*_*

### ISSUE THREAD

**Issue by FollowHeart-Lu** [jrh8182/back-end-management-system#2]
您好，我下载了您的后台管理系统，试图跑起来，搞好环境后springboot可以启动，浏览器访问localhost:9090显示界面是{"code":"401","msg":"无token，请重新登录","data":null}

[](![image](https://user-images.githubusercontent.com/79431161/184496488-7135b1d8-4ad7-43b1-b1e9-813f55030bb9.png))

如果您看到的话可以帮我解答下吗？我目前还没有建数据库

**Comment by jrh8182** [comment]
你好，这是登录验证。因为你没有数据库，所以登录验证不会通过。如果登录通过的话，后端JWT会根据用户名生成一个token，存储在浏览器里。

**Comment by jrh8182** [comment]
> 

这个项目是我跟着b站上的一个毕设视频敲的。
其实这个项目的逻辑不是很好。
你要学习的话可以找好一点的23333，我怕误人子弟。
这里是项目的教程：
https://www.bilibili.com/video/BV1U44y1W77D?share_source=copy_web&vd_source=40779a68857008e13117b4303ecee784

**Comment by jrh8182** [comment]
我已在GitHub上回复，不知你是否看到


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jrh8182/back-end-management-system"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月13日(星期六) 晚上9:36
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[jrh8182/back-end-management-system] 可以帮忙解答一个蠢笨的问题吗*_* (Issue #2)





 
您好，我下载了您的后台管理系统，试图跑起来，搞好环境后springboot可以启动，浏览器访问localhost:9090显示界面是{"code":"401","msg":"无token，请重新登录","data":null}
 

 
如果您看到的话可以帮我解答下吗？我目前还没有建数据库

**Comment by FollowHeart-Lu** [comment]
> 你好，这是登录验证。因为你没有数据库，所以登录验证不会通过。如果登录通过的话，后端JWT会根据用户名生成一个token，存储在浏览器里。

您好，我建立数据库后可以访问到登录页面，可是输入用户名和密码后总是提示用户名或者密码错误，这是什么原因呀？

**Comment by jrh8182** [comment]
> 先通过注册来往用户表里写入信息，才能验证登录呀。你需要的话可以加我qq-1721145407，我把配置需要的sql文件发给你

**Comment by jrh8182** [comment]
你是否学过mybatis 和springboot相关知识呢，没有的话要跑起来有些困难。

**Comment by FollowHeart-Lu** [comment]
> 你是否学过mybatis 和springboot相关知识呢，没有的话要跑起来有些困难。
好的，谢谢您，我加您qq
